### ISSUE TITLE
I get pickle error

### ISSUE THREAD

**Issue by alaikis** [niwinz/django-redis#308] opened 2018-02-14 03:07 UTC
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/site-packages/django_redis/client/default.py", line 313, in decode
    value = int(value)
ValueError: invalid literal for int() with base 10: b'["HTTP_COOKIE"]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/python/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/usr/local/python/lib/python3.6/site-packages/django/middleware/cache.py", line 133, in process_request
    cache_key = get_cache_key(request, self.key_prefix, 'GET', cache=self.cache)
  File "/usr/local/python/lib/python3.6/site-packages/django/utils/cache.py", line 360, in get_cache_key
    headerlist = cache.get(cache_key)
  File "/usr/local/python/lib/python3.6/site-packages/django_redis/cache.py", line 33, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/python/lib/python3.6/site-packages/django_redis/cache.py", line 82, in get
    client=client)
  File "/usr/local/python/lib/python3.6/site-packages/django_redis/client/default.py", line 208, in get
    return self.decode(value)
  File "/usr/local/python/lib/python3.6/site-packages/django_redis/client/default.py", line 320, in decode
    value = self._serializer.loads(value)
  File "/usr/local/python/lib/python3.6/site-packages/django_redis/serializers/pickle.py", line 36, in loads
    return pickle.loads(force_bytes(value))
_pickle.UnpicklingError: invalid load key, '['.
[14/Feb/2018 03:03:10] "GET /scm HTTP/1.1" 500 91657

**Comment by MattBlack85** [comment] 2018-02-14 08:50
I got the exact same error yesterday, I fixed by flushing redis, @alaikis are you using maybe the lock context manager?

**Comment by niwinz** [comment] 2018-03-01 10:21
Hmm withoult a reproducible test case, i can't help much here. Seems like for some reason you have invalid data on the redis database.

**Closed by niwinz** 2018-03-01 10:21 UTC

**Comment by Kazanz** [comment] 2018-06-04 15:47
I have similar issue, albeit on a much earlier version, 3.X `ValueError: unsupported pickle protocol: 4`. 

 Ultimately, there is no mechanism for catching pickle functionality errors.  When the `DJANGO_REDIS_IGNORE_EXCEPTIONS` settings is specified we only catch connection errors:  https://github.com/niwinz/django-redis/blob/master/django_redis/cache.py#L33

Where as this line, could potentially throw pickling errors if the redis data gets corrupted:  https://github.com/niwinz/django-redis/blob/master/django_redis/client/default.py#L317

Design wise, one would expect an `IGNORE_EXCEPTIONS` setting to catch all underlying exceptions/dependencies,  since the ultimate desire for setting this to True is to ignore errors and just re-cache anything that fails/build the data without the cache.  As of right now, the entire app will crash if a pickle related error is raised.  We should either catch Pickle related errors, or have more granular control over the silences exceptions.

**Comment by Kazanz** [comment] 2018-06-04 15:50
I'm moving this comment to a new issue.

**Comment by niwinz** [comment] 2018-06-04 15:52
Completly agree on this. ;) PR welcome
